name: product-management

services:
  backend:
    build:
      context: .  # Root directory (where Dockerfile for backend is located)
      dockerfile: Dockerfile  # Backend Dockerfile is in the root directory
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/product_management
    networks:
      - app-network

  frontend:
    build:
      context: .  # Frontend Dockerfile location
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "8081:80"  # Expose port 80
    depends_on:
      - backend
    # volumes:
    #   - ./FrontEnd:/usr/share/nginx/html/FrontEnd  # Mount the FrontEnd directory for hot reload
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount nginx config for auto-reload
    networks:
      - app-network
  nginx:  # Add this section for Nginx
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure nginx.conf is correctly mapped
      - ./FrontEnd:/usr/share/nginx/html/FrontEnd  # Map your frontend directory to Nginx
    ports:
      - "8080:80"  # Expose port 80 for nginx
    depends_on:
      - frontend
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
