version: '3.8'
name: stratify

services:
  backend:
    env_file: .env.docker
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stratify-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped           # Recommended by big-bro.
    working_dir: /app     # NEW.

  frontend:
    build:
      context: ./FrontEnd  # project-root
      dockerfile: Dockerfile
    container_name: stratify-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"  # This is the only port you need exposed for frontend access
    networks:
      - app-network
    restart: unless-stopped           # Recommended by big-bro.

  # Temporarily Commented as we don't need this right now.  
  # nginx:
  #   image: nginx:latest
  #   container_name: stratify-nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./FrontEnd:/usr/share/nginx/html:ro
  #   ports:
  #     - "8080:80"  # Main exposed port
  #   depends_on:
  #     - frontend
  #   networks:
  #     - app-network
  #   restart: unless-stopped           # Recommended by big-bro.

  mongo:
    image: mongo
    container_name: stratify-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    restart: unless-stopped           # Recommended by big-bro.

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
